version: 0.2

phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - npm run build  # Builds the project
artifacts:
  base-directory: dist/frontend/browser
  files:
    - '**/*'